### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by dcdunkan** [dcdunkan/telegraph#2]
The current documentation (both JSDocs and README) is pretty bad. Of course, I have documented everything. But they are not too good. So we should have some better docs.

- [ ] Better JSDocs.
- [ ] Better and minimal README.
- [ ] ~Move the complete docs to GitHub pages(, maybe?).~
- [ ] Include argument types of methods to Docs.

**Comment by KnorpelSenf** [comment]
I think a comprehensive README could be fine for a project of this scale. It should introduce
- introduce the concepts of this lib
- outline some non-obvious markdown differences
- include a manually written API reference.

If those things are included, I don't think any more docs will be missed.

**Comment by dcdunkan** [comment]
@KnorpelSenf Sure, will do. Thanks!

**Comment by uqe** [comment]
Hey. 

When do you plan to merge this PR?

**Comment by KnorpelSenf** [comment]
Do you mean #6?

**Comment by uqe** [comment]
@KnorpelSenf, yes. 

The current version does not support the `href` attribute for links. I see that [this has been fixed](https://github.com/dcdunkan/telegraph/pull/6/files#diff-7f0e129a9513464e588d401ee4e80ebe29e03238e72fc53258b1c8f31676ff08R99) in #6.

**Comment by KnorpelSenf** [comment]
@dcdunkan?
