### ISSUE TITLE
Node.js Support

### ISSUE THREAD

**Issue by dcdunkan** [dcdunkan/telegraph#3]
It is good to have Node.js support. Should use [deno2node](https://github.com/fromdeno/deno2node).
As mentioned in #1, if the library is going to be used as the dependency of the grammY plugin, we need Node.js support.

**Comment by leaftail1880** [comment]
Hi, I already did this a few months ago, but I didn't know that you were planning to add support for the NodeJS. If you want to take the name of the better-telegraph package in npm, reply to me when you are ready and I will delete my old package

https://npmjs.com/package/better-telegraph

**Comment by dcdunkan** [comment]
Hey @leaftail1880, so sorry for picking this up THIS MUCH late. And I have seen this and the package as well before, but my brain forgot about your comment. Sorry. I've been fixing everything up and finally getting the refactored version merged as well. I came here to close this issue and noticed your comment :(

Thank you for the offer and thanks for porting it and making it accessible. Your package was used in https://github.com/grammyjs/posts for the Node part.

Since this became a requirement for that package, I again started working on this, and I've made improvements and also made it available on JSR (https://jsr.io/) as trying out it for the first time. I may publish a build specifically made for Node in the near future if JSR doesn't fulfill the needs of grammyjs/posts. Then I might contact you for the name, if it becomes a requirement.

Thank you again for the work and the offer! (and sorry for the almost an year delay!) Have a nice day!

Closing this now.

**Comment by leaftail1880** [comment]
Thank you for the response, @dcdunkan! The package is no longer used in my projects, so I abandoned it and I think it would be better for you to take control of it. Tell me your username on npmjs so that I can add you to the maintainers of the package and grant write ability.

**Comment by dcdunkan** [comment]
It's dcdunkan there too. But I don't think I can change the repository linked to the package, right?

**Comment by leaftail1880** [comment]
You can. Repository field is taken from package.json. I've just sent you npm maintainer invintation, once you accept it, i will grant you full write access to the package

**Comment by dcdunkan** [comment]
> Repository field is taken from package.json

I see, thanks. tbh, I don't have any experience with publishing on NPM hehe. Gotta try.

Thank you again for everything, I have accepted the invitation. I'll look into publishing it there (if needed) soon (hopefully).
